### ISSUE TITLE
Nordic Polar folder icons

### ISSUE THREAD

**Issue by m-kru** [EliverLara/Nordic-Polar#11]
Where are Nordic Polar folder icons? In Nordic-Folders.tar.xz there are only Nordic and Nordic -Darker icons.

**Comment by EliverLara** [comment]
Hi, in the screenshots on gnome-look I am using the 'Nordic' folders, but [here](https://github.com/EliverLara/Nordic-Polar/files/4227067/Nordic-Blue.zip)
 are the blue folders I've used before.

**Comment by m-kru** [comment]
Hmm, there are blue icons in the folder, however when I set it the icons from Zafiro are used. After uninstalling Zafiro the icons from Adwaita are used. I have no idea what is going on.

**Comment by EliverLara** [comment]
These files only contain the folders icons, to complement it just edit the `index.theme` file and define the `inherits` key with your favorite icon theme e.g:

`Inherits=your-favorite-icon-theme,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor`

I've made a mix ready to use, you can download it [here](https://drive.google.com/open?id=1FbjXDxEo9Sms0O1ZFnI8s_NTJMl-a62m).

**Comment by m-kru** [comment]
Thanks. I think that Nordic-Blue should be added to the Nordic-Folders.tar.xz on the gnome-look.
