### ISSUE TITLE
Incorrect display of third-party extensions when using Nordic-Polar-40 theme in Ubuntu 23.04

### ISSUE THREAD

**Issue by DameerGamlet** [EliverLara/Nordic-Polar#41]
Bug description:

In the Ubuntu 23.04 operating system, a bug has been detected in the interface related to the Nordic-Polar-40 theme. This problem manifests itself in incorrect display of some third-party extensions, while they are displayed correctly in other themes.

In details, the error is as follows:

When applying the Nordic-Polar-40 theme, some third-party extensions display distorted or improperly arranged interface elements.
The problem is observed only in this particular theme, as there is no error when changing to other themes and extensions are displayed correctly.
Incorrect display may hinder the use and functionality of some extensions, which may affect the user experience.

1) 
![image](https://github.com/EliverLara/Nordic-Polar/assets/74682814/76f526f8-d2fe-42db-8bad-0b29912017be)

2) 
![image](https://github.com/EliverLara/Nordic-Polar/assets/74682814/82451d4b-2f0e-4f26-8c73-751f0766f0dd)

**Comment by DameerGamlet** [comment]
The latest version of the theme is installed

**Comment by DameerGamlet** [comment]
Expected result:
![image](https://github.com/EliverLara/Nordic-Polar/assets/74682814/e036951d-797c-4cec-86c6-f20281d704cd)

It's important to be readable

**Comment by DameerGamlet** [comment]
Also in the conductor is the wrong display of the circuit:
![image](https://github.com/EliverLara/Nordic-Polar/assets/74682814/589a6346-0fd0-4699-8a02-3732f19ab861)

This situation does not apply to the latest version of Nordic-v40.
![image](https://github.com/EliverLara/Nordic-Polar/assets/74682814/16a009ba-1f2a-467e-997d-a07005a7217e)

**Comment by EliverLara** [comment]
Hi, what extensions are you using? So I could check the issue

**Comment by DameerGamlet** [comment]
Extensions: Vitals(https://extensions.gnome.org/extension/1460/vitals/) and Easy Docker Containers (https://extensions.gnome.org/extension/2224/easy-docker-containers/)

But I can assume that this can also be found in other extensions and the solution would be to change the color palette (since I'm not a developer, I could be wrong).

**Comment by DameerGamlet** [comment]
Thank you very much. Everything works and looks just as I wanted it to.
![image](https://github.com/EliverLara/Nordic-Polar/assets/74682814/16e685cf-eb07-4701-93ce-1ac1c78560d9)

**Comment by DameerGamlet** [comment]
But he still thinks Nordic-polar is a light theme

**Comment by DameerGamlet** [comment]
But with the Nordic-bluish-accent theme, the problem is solved (looks just right to me).

So I can assume that the problem is solved. Thanks again

**Comment by EliverLara** [comment]
It's awesome the fix works for you :) It would be great if you have some free time that you could help me by writing a review on the [gnome-look](https://www.gnome-look.org/p/1267246/) page, it would help me a lot since I've been recently atacked by some fake accounts trying to defame my themes.
