### ISSUE TITLE
System Load Monitor On Tray Panel

### ISSUE THREAD

**Issue by bligidig** [EliverLara/Nordic-Polar#42]
Hi @EliverLara 

I have noticed that my System Load Monitor' text becomes unreadable on Nordic Polar, but it's readable on Nordic. How can I make it readable on Nordic Polar as just like on Nordic? The screenshot are as like follows;

1.1) System Load Monitor on Nordic
![system-load-monitor_on_nordic](https://github.com/EliverLara/Nordic-Polar/assets/134568353/dd16d3b3-571a-4560-ac06-c7028081f2d1)

1.2) System Load Monitor on Nordic Polar
![system-load-monitor_on_nordic-polar](https://github.com/EliverLara/Nordic-Polar/assets/134568353/5abfa8f1-798e-4a7b-935f-f7fcb7e35e01)

Thank you

**Comment by bligidig** [comment]
Hi @EliverLara 

Is there any fixes from you about [this](https://github.com/EliverLara/Nordic-Polar/issues/42#issue-1785171278) issue? Thank you

**Comment by EliverLara** [comment]
HI, Could you provide more info about your OS, please?

**Comment by bligidig** [comment]
> HI, Could you provide more info about your OS, please? I'd also know if you're using the latest version released on [gnome-look](https://www.pling.com/p/1267246/)

Hi @EliverLara , here is the info about the OS 

```
[CODE] Kernel: 6.5.0-1mx-ahs-amd64 [6.5.3-1~mx23ahs] arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-6.5.0-1mx-ahs-amd64 root=UUID=<filter> ro quiet
    resume=UUID=<filter> resume_offset=786432
  Desktop: Xfce v: 4.18.1 tk: Gtk v: 3.24.36 info: xfce4-panel wm: xfwm v: 4.18.0 vt: 7 dm:
    1: GDM3 v: 43.0 2: LightDM v: 1.26.0 Distro: MX-23.1_ahs_x64 Libretto July 31  2023 base: Debian
    GNU/Linux 12 (bookworm)[/CODE]
```
Is the above mentioned is what you mean?

As for the version, I think I am already at your latest released version
![ss_20231127-081233](https://github.com/EliverLara/Nordic-Polar/assets/134568353/5d699b4d-7f01-4b43-8643-ffce261713b9)

Thank you
