### ISSUE TITLE
Request for Dark Variant

### ISSUE THREAD

**Issue by lokesh-krishna** [EliverLara/Nordic-Polar#7]
Could you please consider also offering a dark variant of this theme? Like the Nordic theme but using this accent color?

You've done an absolutely brilliant job with these themes! I've been in love with the Nord color scheme for years now and have long wanted a good GTK theme for it and this has been a dream come true.

**Comment by EliverLara** [comment]
Hi,the version you require(Nordic-bluish-accent) already exists on [gnome-look](https://www.gnome-look.org/p/1267246/)

**Comment by lokesh-krishna** [comment]
That is a very pleasant surprise!
Should I close this issue or can it remain open as a request to maybe also share that theme here?

**Comment by romildo** [comment]
I package this theme for [NixOS](https://nixos.org/) from the releases on github. I second @lokesh-krishna request to make those variants available here, so that they can be included in the package for NixOS too.

**Comment by darthoctopus** [comment]
@EliverLara I think a more specific request would be to include the dark version nordic-bluish-accent as the gtk-dark.css provided by this theme, so that it respects dark theme preferences.

**Comment by EliverLara** [comment]
@darthoctopus that makes sense, I will add it as `gtk-dark.css` for this theme too.

**Comment by EliverLara** [comment]
@lokesh-krishna @romildo that theme is also available on github as a [Nordic theme branch](https://github.com/EliverLara/Nordic/tree/bluish-accent)
